### ISSUE TITLE
Teamcity plugin does not extract email address of the committer

### ISSUE THREAD

**Issue by sangyum** [n0rad/visuwall#15]
Hi, thanks for the awesome project. I have been using Visuwall as our Teamcity Dashboard for the last month or so and it's awesome!

I do have one issue. I would like to be able to take full advantage of Gravatar integration but, as far as I can tell, Teamcity plugin does not pull the email address of the commiter. When I sniffed the traffic, Teamcity is indeed returning email address but it gets lost along the way.

I would have made the fix myself but could not build the project completely under IntelliJ due to missing   dependencies.

Can you please help?

Thanks.

**Comment by n0rad** [comment]
Can you test the version on master ? you should not have problems with dependencies and gravatar should be working.

The email is taken from the teamcity users.

**Comment by sangyum** [comment]
I just cloned from master and was able to build it locally. When I examine the response coming from visuwall, the commiters info is still missing name and email

"builds":{"4602":{"state":"SUCCESS","duration":241000,"commiters":[{"name":null,"id":"ourdomain\omora","email":null}],"unitTestResult":{"totalCount":0,"skipCount":0,"passCount":0,"failCount":0,"coverage":0.0},"integrationTestResult":{"totalCount":0,"skipCount":0,"passCount":0,"failCount":0,"coverage":0.0}

**Comment by n0rad** [comment]
Teamcity may not have commiters on each build if you run it manually for example.
Also I think visuwall will try to get the commiters for each build but will display the avatar only on failure/unstable.

If you teamcity is public, can you give me the url.
If it's private, Can you give me the output of this url :

```
http://TEAMCITY:PORT/app/rest/changes?build=id:4602
```

The output of each <change href="...."> link

And the output of this link for all username you will find in the previous payloads 

```
http://TEAMCITY:PORT/app/rest/users/username:USERNAME
```

If you don't want to drop it here you can send it by mail

**Comment by sangyum** [comment]
n0rad, thanks for the reply. 

build info contained userid's in the formation of "<windows domain><user id>". When that user id was included as is in the second query, Teamcity returned not found.

I need to figure out how to configure Teamcity to return the user id without the domain prefix. 

Thanks for your help!
